version: '3'
services:
  chatbot:
    build: .
    command: python src/app.py
    ports:
      - "5000:5000"
    env_file:
      - ./src/.env

  indexer:
    build: .
    command: python src/indexer.py
    env_file:
      - ./src/.env
